export const actionTypes = {
    LOGIN: 'LOGIN',
    LOGOUT:'LOGOUT',
    REGISTER: 'REGISTER',
    UNREGISTER:'UNREGISTER',
    ADDDETAILS: 'ADDDETAILS',
    UPDATEDETAILS: 'UPDATEDETAILS',
    DELETEDETAILS: 'DELETEDETAILS',
    GETSTUDENT: 'GETSTUDENT',
    STUDENTPHOTO: 'STUDENTPHOTO',
    GETPHOTO: 'GETPHOTO'
  }